namespace ValheimCreative.Features.Creative
{
    internal static class CreativeEnvironmentDefaultPolicy
    {
        internal const string Contents = @"# Creative terrain and vegetation policy.
# Resolution order: defaults -> biomes.<activeBiome> -> zones.<slotId>.
# Vegetation requires terrain. If terrain is disabled, vegetation is forced off.
defaults:
  terrain:
    enabled: true
  vegetation:
    enabled: true
    preset: defaultMeadows
    dropsEnabled: false

biomes:
  Meadows:
    vegetation:
      preset: defaultMeadows
  BlackForest:
    vegetation:
      preset: defaultBlackForest
  Swamp:
    vegetation:
      preset: defaultSwamp
  Mountain:
    vegetation:
      preset: defaultMountain
  Plains:
    vegetation:
      preset: defaultPlains
  Mistlands:
    vegetation:
      preset: defaultMistlands
  AshLands:
    vegetation:
      preset: defaultAshLands
  DeepNorth:
    vegetation:
      preset: defaultDeepNorth
  Ocean:
    vegetation:
      preset: defaultOcean

zones: {}
# Example per-zone override:
# zones:
#   creative_000:
#     terrain:
#       enabled: true
#     vegetation:
#       enabled: true
#       preset: sparseMeadows
#       dropsEnabled: false

presets:
  defaultMeadows:
    entries:
      - name: Meadows_01_rock4_coast
        prefab: rock4_coast
        biome: Meadows
        biomeArea: Edge,Median
        min: 3
        max: 3
        groupSizeMin: 3
        groupSizeMax: 3
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: -0.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 2
        maxOceanDepth: 30
        minTilt: 0
        maxTilt: 90
      - name: Meadows_02_Rock_4
        prefab: Rock_4
        biome: Meadows
        biomeArea: Edge,Median
        min: 10
        max: 40
        scaleMin: 1
        scaleMax: 2
        minAltitude: -10
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Meadows_03_Rock_3
        prefab: Rock_3
        biome: Meadows
        biomeArea: Edge,Median
        min: 0
        max: 15
        scaleMin: 2
        scaleMax: 4
        groundOffset: -0.5
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Meadows_04_Beech1
        prefab: Beech1
        biome: Meadows
        biomeArea: Edge,Median
        min: 40
        max: 40
        scaleMin: 0.8
        scaleMax: 1.5
        minAltitude: 0.2
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: Meadows_05_Birch1
        prefab: Birch1
        biome: Meadows
        biomeArea: Edge,Median
        min: 5
        max: 5
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0.2
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: Meadows_06_Birch2
        prefab: Birch2
        biome: Meadows
        biomeArea: Edge,Median
        min: 0
        max: 3
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0.2
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: Meadows_07_Oak1
        prefab: Oak1
        biome: Meadows
        biomeArea: Edge,Median
        min: 0
        max: 1
        scaleMin: 0.8
        scaleMax: 1
        minAltitude: 0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 20
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 3
      - name: Meadows_08_Beech_small1
        prefab: Beech_small1
        biome: Meadows
        biomeArea: Edge,Median
        min: 100
        max: 100
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
        inForest: true
        forestTresholdMin: 1.1
        forestTresholdMax: 1.15
      - name: Meadows_09_Beech_small2
        prefab: Beech_small2
        biome: Meadows
        biomeArea: Edge,Median
        min: 100
        max: 100
        scaleMin: 1
        scaleMax: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
        inForest: true
        forestTresholdMin: 1.1
        forestTresholdMax: 1.15
      - name: Meadows_10_Beech_small1
        prefab: Beech_small1
        biome: Meadows
        biomeArea: Edge,Median
        min: 80
        max: 80
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Meadows_11_Beech_small2
        prefab: Beech_small2
        biome: Meadows
        biomeArea: Edge,Median
        min: 80
        max: 80
        scaleMin: 1
        scaleMax: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Meadows_12_stubbe
        prefab: stubbe
        biome: Meadows
        biomeArea: Edge,Median
        min: 1
        max: 3
        scaleMin: 0.8
        scaleMax: 1.2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 20
      - name: Meadows_13_FirTree_oldLog
        prefab: FirTree_oldLog
        biome: Meadows
        biomeArea: Edge,Median
        min: 1
        max: 4
        scaleMin: 1
        scaleMax: 1.2
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: Meadows_14_Bush01
        prefab: Bush01
        biome: Meadows
        biomeArea: Edge,Median
        min: 60
        max: 80
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 1.15
      - name: Meadows_15_RaspberryBush
        prefab: RaspberryBush
        biome: Meadows
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 3
        groupSizeMax: 8
        groupRadius: 8
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 1.2
      - name: Meadows_16_Pickable_Mushroom
        prefab: Pickable_Mushroom
        biome: Meadows
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 3
        groupSizeMax: 6
        groupRadius: 5
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 25
      - name: Meadows_17_Pickable_Dandelion
        prefab: Pickable_Dandelion
        biome: Meadows
        biomeArea: Edge,Median
        min: 8
        max: 10
        groupSizeMin: 1
        groupSizeMax: 3
        groupRadius: 3
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 15
      - name: Meadows_18_Pickable_Flint
        prefab: Pickable_Flint
        biome: Meadows
        biomeArea: Edge,Median
        min: 30
        max: 30
        minAltitude: -2
        maxAltitude: 1
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Meadows_19_Pickable_Branch
        prefab: Pickable_Branch
        biome: Meadows
        biomeArea: Edge,Median
        min: 15
        max: 15
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Meadows_20_Pickable_Stone
        prefab: Pickable_Stone
        biome: Meadows
        biomeArea: Edge,Median
        min: 30
        max: 30
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 22
        maxTilt: 90
      - name: Meadows_21_Pickable_Stone
        prefab: Pickable_Stone
        biome: Meadows
        biomeArea: Edge,Median
        min: 5
        max: 5
        minAltitude: -3
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Meadows_22_Pickable_StoneRock
        prefab: Pickable_StoneRock
        biome: Meadows
        biomeArea: Median
        min: 0
        max: 1
        minAltitude: 5
        maxAltitude: 20
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90

  defaultBlackForest:
    entries:
      - name: BlackForest_01_rock4_coast
        prefab: rock4_coast
        biome: BlackForest
        biomeArea: Edge,Median
        min: 3
        max: 3
        groupSizeMin: 3
        groupSizeMax: 3
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: -0.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 2
        maxOceanDepth: 30
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_02_rock4_forest
        prefab: rock4_forest
        biome: BlackForest
        biomeArea: Edge,Median
        min: 1
        max: 2
        scaleMin: 0.8
        scaleMax: 1
        groundOffset: -2
        minAltitude: 4
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 5
        maxTilt: 45
      - name: BlackForest_03_rock4_copper
        prefab: rock4_copper
        biome: BlackForest
        biomeArea: Edge,Median
        min: 0
        max: 1
        groundOffset: -2
        minAltitude: 4
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 5
        maxTilt: 45
      - name: BlackForest_04_MineRock_Tin
        prefab: MineRock_Tin
        biome: BlackForest
        biomeArea: Edge,Median
        min: 20
        max: 20
        groundOffset: -0.5
        minAltitude: -0.6
        maxAltitude: 1.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_05_Rock_4
        prefab: Rock_4
        biome: BlackForest
        biomeArea: Edge,Median
        min: 20
        max: 20
        scaleMin: 1
        scaleMax: 3
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
      - name: BlackForest_06_Rock_3
        prefab: Rock_3
        biome: BlackForest
        biomeArea: Edge,Median
        min: 5
        max: 15
        scaleMin: 3
        scaleMax: 6
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25
      - name: BlackForest_07_FirTree
        prefab: FirTree
        biome: BlackForest
        biomeArea: Edge,Median
        min: 5
        max: 5
        scaleMin: 2
        scaleMax: 2.5
        minAltitude: 0.1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: BlackForest_08_FirTree
        prefab: FirTree
        biome: BlackForest
        biomeArea: Edge
        min: 40
        max: 40
        scaleMin: 2
        scaleMax: 2.5
        minAltitude: 0.1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: BlackForest_09_Pinetree_01
        prefab: Pinetree_01
        biome: BlackForest
        biomeArea: Median
        min: 60
        max: 60
        scaleMin: 1
        scaleMax: 2.5
        minAltitude: 0.1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 1.5
        minTilt: 0
        maxTilt: 30
      - name: BlackForest_10_FirTree_small
        prefab: FirTree_small
        biome: BlackForest
        biomeArea: Edge,Median
        min: 30
        max: 30
        scaleMin: 0.3
        scaleMax: 0.7
        minAltitude: 0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: BlackForest_11_FirTree_small
        prefab: FirTree_small
        biome: BlackForest
        biomeArea: Edge
        min: 60
        max: 60
        scaleMin: 0.3
        scaleMax: 0.7
        minAltitude: 0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: BlackForest_12_FirTree_oldLog
        prefab: FirTree_oldLog
        biome: BlackForest
        biomeArea: Edge,Median
        min: 6
        max: 6
        scaleMin: 0.9
        scaleMax: 1.3
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25
      - name: BlackForest_13_stubbe
        prefab: stubbe
        biome: BlackForest
        biomeArea: Edge,Median
        min: 15
        max: 15
        scaleMin: 0.8
        scaleMax: 1.4
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 20
      - name: BlackForest_14_Pickable_Thistle
        prefab: Pickable_Thistle
        biome: BlackForest
        biomeArea: Median
        min: 1
        max: 2
        groupSizeMin: 2
        groupSizeMax: 5
        groupRadius: 4
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: BlackForest_15_shrub_2
        prefab: shrub_2
        biome: BlackForest
        biomeArea: Edge,Median
        min: 100
        max: 100
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_16_BlueberryBush
        prefab: BlueberryBush
        biome: BlackForest
        biomeArea: Median
        min: 1
        max: 1
        groupSizeMin: 1
        groupSizeMax: 8
        groupRadius: 8
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_17_Pickable_Mushroom
        prefab: Pickable_Mushroom
        biome: BlackForest
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 3
        groupSizeMax: 6
        groupRadius: 5
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 25
      - name: BlackForest_18_Pickable_Branch
        prefab: Pickable_Branch
        biome: BlackForest
        biomeArea: Edge,Median
        min: 15
        max: 15
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_19_Pickable_Stone
        prefab: Pickable_Stone
        biome: BlackForest
        biomeArea: Edge,Median
        min: 30
        max: 30
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 22
        maxTilt: 90
      - name: BlackForest_20_Pickable_StoneRock
        prefab: Pickable_StoneRock
        biome: BlackForest
        biomeArea: Median
        min: 0
        max: 1
        minAltitude: 5
        maxAltitude: 20
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: BlackForest_21_Pickable_SeedCarrot
        prefab: Pickable_SeedCarrot
        biome: BlackForest
        biomeArea: Edge,Median
        min: 0
        max: 0.5
        groupSizeMin: 1
        groupSizeMax: 2
        groupRadius: 5
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25

  defaultSwamp:
    entries:
      - name: Swamp_01_Rock_4
        prefab: Rock_4
        biome: Swamp
        biomeArea: Edge,Median
        min: 0
        max: 20
        scaleMin: 1
        scaleMax: 2
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_02_mudpile_beacon
        prefab: mudpile_beacon
        biome: Swamp
        biomeArea: Edge,Median
        min: 0
        max: 5
        scaleMin: 1
        scaleMax: 2
        groundOffset: -3
        minAltitude: 0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_03_vfx_swamp_mist
        prefab: vfx_swamp_mist
        biome: Swamp
        biomeArea: Edge,Median
        min: 10
        max: 10
        snapToWater: true
        minAltitude: -5
        maxAltitude: 5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_04_FirTree_small_dead
        prefab: FirTree_small_dead
        biome: Swamp
        biomeArea: Edge,Median
        min: 60
        max: 60
        scaleMin: 0.3
        scaleMax: 0.8
        minAltitude: 0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25
      - name: Swamp_05_SwampTree1
        prefab: SwampTree1
        biome: Swamp
        biomeArea: Edge,Median
        min: 40
        max: 40
        scaleMin: 0.7
        scaleMax: 1.3
        minAltitude: -0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 30
      - name: Swamp_06_SwampTree2
        prefab: SwampTree2
        biome: Swamp
        biomeArea: Edge,Median
        min: 10
        max: 20
        scaleMin: 1.5
        scaleMax: 2
        minAltitude: -0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 35
      - name: Swamp_07_SwampTree2_log
        prefab: SwampTree2_log
        biome: Swamp
        biomeArea: Edge,Median
        min: 1
        max: 3
        scaleMin: 1.5
        scaleMax: 2
        minAltitude: -0.5
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 35
      - name: Swamp_08_Flies
        prefab: Flies
        biome: Swamp
        biomeArea: Edge,Median
        min: 20
        max: 20
        scaleMin: 0.5
        scaleMax: 1.5
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25
      - name: Swamp_09_stubbe
        prefab: stubbe
        biome: Swamp
        biomeArea: Edge,Median
        min: 4
        max: 4
        scaleMin: 1
        scaleMax: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 20
      - name: Swamp_10_StatueEvil
        prefab: StatueEvil
        biome: Swamp
        biomeArea: Edge,Median
        min: 2
        max: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: Swamp_11_FirTree_oldLog
        prefab: FirTree_oldLog
        biome: Swamp
        biomeArea: Edge,Median
        min: 6
        max: 6
        scaleMin: 1
        scaleMax: 1.2
        minAltitude: -1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: Swamp_12_shrub_2_heath
        prefab: shrub_2_heath
        biome: Swamp
        biomeArea: Edge,Median
        min: 20
        max: 20
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 90
      - name: Swamp_13_Pickable_Thistle
        prefab: Pickable_Thistle
        biome: Swamp
        biomeArea: Median
        min: 1
        max: 2
        groupSizeMin: 2
        groupSizeMax: 5
        groupRadius: 4
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: Swamp_14_Pickable_Mushroom
        prefab: Pickable_Mushroom
        biome: Swamp
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 3
        groupSizeMax: 6
        groupRadius: 5
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 2
        minTilt: 0
        maxTilt: 25
      - name: Swamp_15_Pickable_Branch
        prefab: Pickable_Branch
        biome: Swamp
        biomeArea: Edge,Median
        min: 15
        max: 15
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_16_Pickable_Stone
        prefab: Pickable_Stone
        biome: Swamp
        biomeArea: Edge,Median
        min: 30
        max: 30
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 22
        maxTilt: 90
      - name: Swamp_17_Pickable_Stone
        prefab: Pickable_Stone
        biome: Swamp
        biomeArea: Edge,Median
        min: 5
        max: 5
        minAltitude: -3
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_18_Pickable_StoneRock
        prefab: Pickable_StoneRock
        biome: Swamp
        biomeArea: Median
        min: 0
        max: 1
        minAltitude: 5
        maxAltitude: 20
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Swamp_19_Pickable_SeedTurnip
        prefab: Pickable_SeedTurnip
        biome: Swamp
        biomeArea: Edge,Median
        min: 0
        max: 0.5
        groupSizeMin: 1
        groupSizeMax: 2
        groupRadius: 5
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25

  defaultMountain:
    entries:
      - name: Mountain_01_rock3_mountain
        prefab: rock3_mountain
        biome: Mountain
        biomeArea: Median
        min: 0
        max: 2
        scaleMin: 1
        scaleMax: 1.5
        groundOffset: -5
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 10
        maxTilt: 50
      - name: Mountain_02_silvervein
        prefab: silvervein
        biome: Mountain
        biomeArea: Median
        min: 1
        max: 1
        groundOffset: -4
        minAltitude: 120
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 3
        terrainDeltaRadius: 9
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mountain_03_rock1_mountain
        prefab: rock1_mountain
        biome: Mountain
        biomeArea: Median
        min: 5
        max: 8
        scaleMin: 1
        scaleMax: 1.5
        groundOffset: -6
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 30
        maxTilt: 80
      - name: Mountain_04_rock2_mountain
        prefab: rock2_mountain
        biome: Mountain
        biomeArea: Median
        min: 5
        max: 8
        scaleMin: 1
        scaleMax: 1.5
        groundOffset: -5
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 30
        maxTilt: 80
      - name: Mountain_05_Rock_4
        prefab: Rock_4
        biome: Mountain
        biomeArea: Edge,Median
        min: 10
        max: 40
        scaleMin: 1
        scaleMax: 2
        minAltitude: -10
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Mountain_06_Rock_3
        prefab: Rock_3
        biome: Mountain
        biomeArea: Edge,Median
        min: 0
        max: 15
        scaleMin: 2
        scaleMax: 4
        groundOffset: -0.5
        minAltitude: -1000
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Mountain_07_FirTree_small
        prefab: FirTree_small
        biome: Mountain
        biomeArea: Edge,Median
        min: 30
        max: 30
        scaleMin: 0.3
        scaleMax: 0.7
        minAltitude: 0
        maxAltitude: 280
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mountain_08_Pickable_StoneRock
        prefab: Pickable_StoneRock
        biome: Mountain
        biomeArea: Median
        min: 0
        max: 1
        minAltitude: 5
        maxAltitude: 20
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Mountain_09_FirTree
        prefab: FirTree
        biome: Mountain
        biomeArea: Edge,Median
        min: 5
        max: 20
        scaleMin: 1.5
        scaleMax: 3
        minAltitude: 2
        maxAltitude: 280
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mountain_10_MineRock_Obsidian
        prefab: MineRock_Obsidian
        biome: Mountain
        biomeArea: Edge,Median
        min: 10
        max: 15
        scaleMin: 0.9
        scaleMax: 1
        minAltitude: 100
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90

  defaultPlains:
    entries:
      - name: Plains_01_rock4_heath
        prefab: rock4_heath
        biome: Plains
        biomeArea: Edge,Median
        min: 4
        max: 10
        scaleMin: 0.8
        scaleMax: 1
        groundOffset: -3
        minAltitude: 4
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 15
        maxTilt: 45
      - name: Plains_02_HeathRockPillar
        prefab: HeathRockPillar
        biome: Plains
        biomeArea: Edge,Median
        min: 0
        max: 0.1
        scaleMin: 0.8
        scaleMax: 1.3
        groundOffset: -2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Plains_03_rock2_heath
        prefab: rock2_heath
        biome: Plains
        biomeArea: Edge,Median
        min: 0
        max: 1
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: Plains_04_Rock_4_plains
        prefab: Rock_4_plains
        biome: Plains
        biomeArea: Edge,Median
        min: 5
        max: 30
        scaleMin: 1
        scaleMax: 2
        minAltitude: -10
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: Plains_05_Birch1_aut
        prefab: Birch1_aut
        biome: Plains
        biomeArea: Edge,Median
        min: 30
        max: 30
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0.1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
        inForest: true
        forestTresholdMin: 0
        forestTresholdMax: 0.8
      - name: Plains_06_Birch2_aut
        prefab: Birch2_aut
        biome: Plains
        biomeArea: Edge,Median
        min: 10
        max: 10
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 0.1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
        inForest: true
        forestTresholdMin: 0
        forestTresholdMax: 0.8
      - name: Plains_07_Bush02_en
        prefab: Bush02_en
        biome: Plains
        biomeArea: Edge,Median
        min: 1
        max: 3
        groupSizeMin: 8
        groupSizeMax: 20
        groupRadius: 15
        scaleMin: 0.5
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Plains_08_CloudberryBush
        prefab: CloudberryBush
        biome: Plains
        biomeArea: Edge,Median
        min: 1
        max: 3
        groupSizeMin: 15
        groupSizeMax: 20
        groupRadius: 6
        minAltitude: 2
        maxAltitude: 50
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Plains_09_Bush01_heath
        prefab: Bush01_heath
        biome: Plains
        biomeArea: Edge,Median
        min: 60
        max: 80
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 1.15
      - name: Plains_10_shrub_2_heath
        prefab: shrub_2_heath
        biome: Plains
        biomeArea: Edge,Median
        min: 20
        max: 20
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 1.15
      - name: Plains_11_Pickable_Stone
        prefab: Pickable_Stone
        biome: Plains
        biomeArea: Edge,Median
        min: 30
        max: 30
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 2
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 22
        maxTilt: 90

  defaultMistlands:
    entries:
      - name: Mistlands_01_rock4_coast
        prefab: rock4_coast
        biome: Mistlands
        biomeArea: Edge,Median
        min: 3
        max: 3
        groupSizeMin: 3
        groupSizeMax: 3
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: -0.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 2
        maxOceanDepth: 30
        minTilt: 0
        maxTilt: 90
      - name: Mistlands_02_MistArea
        prefab: MistArea
        biome: Mistlands
        biomeArea: Median
        min: 1
        max: 1
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: Mistlands_03_MistArea_edge
        prefab: MistArea_edge
        biome: Mistlands
        biomeArea: Edge
        min: 1
        max: 1
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: Mistlands_04_cliff_mistlands1
        prefab: cliff_mistlands1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 8
        max: 8
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 4
        maxTerrainDelta: 55
        terrainDeltaRadius: 4
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 25
        maxTilt: 50
      - name: Mistlands_05_cliff_mistlands2
        prefab: cliff_mistlands2
        biome: Mistlands
        biomeArea: Edge,Median
        min: 50
        max: 50
        scaleMin: 0.5
        scaleMax: 1
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 3
        maxTerrainDelta: 55
        terrainDeltaRadius: 4
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: Mistlands_06_rock_mistlands1
        prefab: rock_mistlands1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 20
        max: 20
        scaleMin: 1
        scaleMax: 3
        minAltitude: 0
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 4
        terrainDeltaRadius: 2
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mistlands_07_giant_helmet1
        prefab: giant_helmet1
        biome: Mistlands
        biomeArea: Median
        min: 1
        max: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 3
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mistlands_08_giant_helmet2
        prefab: giant_helmet2
        biome: Mistlands
        biomeArea: Median
        min: 1
        max: 2
        groundOffset: -1
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 3
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mistlands_09_giant_sword1
        prefab: giant_sword1
        biome: Mistlands
        biomeArea: Median
        min: 1
        max: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 3
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mistlands_10_giant_sword2
        prefab: giant_sword2
        biome: Mistlands
        biomeArea: Median
        min: 1
        max: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 3
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: Mistlands_11_giant_ribs
        prefab: giant_ribs
        biome: Mistlands
        biomeArea: Edge,Median
        min: 1
        max: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 10
      - name: Mistlands_12_YggdrasilRoot
        prefab: YggdrasilRoot
        biome: Mistlands
        biomeArea: Edge,Median
        min: 2
        max: 4
        scaleMin: 1
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 6
        terrainDeltaRadius: 5
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
      - name: Mistlands_13_YggaShoot1
        prefab: YggaShoot1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 2
        max: 2
        scaleMin: 0.9
        scaleMax: 1.2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 3
        maxTerrainDelta: 99
        terrainDeltaRadius: 3
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 80
      - name: Mistlands_14_YggaShoot2
        prefab: YggaShoot2
        biome: Mistlands
        biomeArea: Edge,Median
        min: 2
        max: 2
        scaleMin: 0.9
        scaleMax: 1.2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 3
        maxTerrainDelta: 99
        terrainDeltaRadius: 3
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 80
      - name: Mistlands_15_YggaShoot3
        prefab: YggaShoot3
        biome: Mistlands
        biomeArea: Edge,Median
        min: 2
        max: 2
        scaleMin: 0.9
        scaleMax: 1.2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 3
        maxTerrainDelta: 99
        terrainDeltaRadius: 3
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 80
      - name: Mistlands_16_YggaShoot1
        prefab: YggaShoot1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 3
        max: 3
        scaleMin: 0.8
        scaleMax: 0.9
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 4
      - name: Mistlands_17_YggaShoot2
        prefab: YggaShoot2
        biome: Mistlands
        biomeArea: Edge,Median
        min: 3
        max: 3
        scaleMin: 0.8
        scaleMax: 0.9
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 4
      - name: Mistlands_18_YggaShoot3
        prefab: YggaShoot3
        biome: Mistlands
        biomeArea: Edge,Median
        min: 3
        max: 3
        scaleMin: 0.8
        scaleMax: 0.9
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 4
      - name: Mistlands_19_YggaShoot_small1
        prefab: YggaShoot_small1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 6
        max: 6
        scaleMin: 1
        scaleMax: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
      - name: Mistlands_20_YggaShoot_small1
        prefab: YggaShoot_small1
        biome: Mistlands
        biomeArea: Edge,Median
        min: 40
        max: 40
        scaleMin: 1
        scaleMax: 2
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 45
        inForest: true
        forestTresholdMin: 1
        forestTresholdMax: 4
      - name: Mistlands_21_Pickable_Mushroom_Magecap
        prefab: Pickable_Mushroom_Magecap
        biome: Mistlands
        biomeArea: Edge,Median
        min: 2
        max: 2
        groupSizeMin: 1
        groupSizeMax: 3
        groupRadius: 5
        minAltitude: 1
        maxAltitude: 2000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 60
      - name: Mistlands_22_Pickable_Mushroom_JotunPuffs
        prefab: Pickable_Mushroom_JotunPuffs
        biome: Mistlands
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 1
        groupSizeMax: 3
        groupRadius: 5
        minAltitude: 1
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 60

  defaultAshLands:
    entries:
      - name: AshLands_01_cliff_ashlands2
        prefab: cliff_ashlands2
        biome: AshLands
        biomeArea: Edge,Median
        min: 0
        max: 1
        scaleMin: 0.5
        scaleMax: 1.5
        minAltitude: 1
        maxAltitude: 15
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_02_cliff_ashlands3_Arch_1
        prefab: cliff_ashlands3_Arch_1
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 3
        scaleMin: 1
        scaleMax: 2
        minAltitude: 0
        maxAltitude: 40
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 10
        maxTilt: 40
      - name: AshLands_03_cliff_ashlands5
        prefab: cliff_ashlands5
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 3
        scaleMin: 0.2
        scaleMax: 1.5
        minAltitude: 0
        maxAltitude: 100
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 60
      - name: AshLands_04_cliff_ashlands5
        prefab: cliff_ashlands5
        biome: AshLands
        biomeArea: Edge,Median
        min: 3
        max: 5
        scaleMin: 0.8
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: 1
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 60
      - name: AshLands_05_cliff_ashlands6
        prefab: cliff_ashlands6
        biome: AshLands
        biomeArea: Edge,Median
        min: 3
        max: 6
        scaleMin: 0.5
        scaleMax: 0.9
        minAltitude: -5
        maxAltitude: 10
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 10
        maxTilt: 40
      - name: AshLands_06_cliff_ashlands4
        prefab: cliff_ashlands4
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 3
        groupSizeMin: 2
        groupSizeMax: 5
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 0.8
        groundOffset: -2
        minAltitude: -10
        maxAltitude: 0.1
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: AshLands_07_cliff_ashlands4
        prefab: cliff_ashlands4
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 3
        groupSizeMin: 2
        groupSizeMax: 5
        groupRadius: 27
        scaleMin: 0.9
        scaleMax: 1.1
        groundOffset: -1
        minAltitude: -25
        maxAltitude: -11
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 20
      - name: AshLands_08_AshlandsTree1
        prefab: AshlandsTree1
        biome: AshLands
        biomeArea: Edge,Median
        min: 6
        max: 10
        groupSizeMin: 4
        groupSizeMax: 8
        groupRadius: 40
        scaleMin: 0.7
        scaleMax: 1.4
        minAltitude: 2
        maxAltitude: 12
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: AshLands_09_AshlandsTree1
        prefab: AshlandsTree1
        biome: AshLands
        biomeArea: Edge,Median
        min: 5
        max: 8
        groupSizeMin: 2
        groupSizeMax: 4
        groupRadius: 40
        minAltitude: 1
        maxAltitude: 12
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: AshLands_10_AshlandsTree3
        prefab: AshlandsTree3
        biome: AshLands
        biomeArea: Edge,Median
        min: 4
        max: 10
        groupSizeMin: 3
        groupSizeMax: 5
        groupRadius: 50
        scaleMin: 1
        scaleMax: 2
        minAltitude: 1
        maxAltitude: 12
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 30
      - name: AshLands_11_AshlandsTree6
        prefab: AshlandsTree6
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 3
        scaleMin: 1.5
        scaleMax: 2.5
        minAltitude: 1
        maxAltitude: 12
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 10
      - name: AshLands_12_Ashlands_rock2
        prefab: Ashlands_rock2
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 0.6
        scaleMin: 0.8
        scaleMax: 1
        minAltitude: 4
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 25
      - name: AshLands_13_cliff_ashlands6
        prefab: cliff_ashlands6
        biome: AshLands
        biomeArea: Edge,Median
        min: 92
        max: 196
        scaleMin: 0.2
        scaleMax: 0.9
        minAltitude: 9
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_14_AshlandsBranch1
        prefab: AshlandsBranch1
        biome: AshLands
        biomeArea: Edge,Median
        min: 4
        max: 6
        groupSizeMin: 3
        groupSizeMax: 5
        groupRadius: 30
        scaleMin: 1
        scaleMax: 3
        minAltitude: 1
        maxAltitude: 6
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_15_AshlandsBranch2
        prefab: AshlandsBranch2
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 3
        scaleMin: 0.8
        scaleMax: 1
        minAltitude: 1
        maxAltitude: 7
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_16_AshlandsBranch3
        prefab: AshlandsBranch3
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 3
        groupSizeMin: 2
        groupSizeMax: 4
        groupRadius: 30
        scaleMin: 0.8
        scaleMax: 1
        minAltitude: 1
        maxAltitude: 6
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_17_AshlandsBush1
        prefab: AshlandsBush1
        biome: AshLands
        biomeArea: Edge,Median
        min: 6
        max: 10
        groupSizeMin: 2
        groupSizeMax: 4
        groupRadius: 0
        scaleMin: 1
        scaleMax: 3
        minAltitude: 1
        maxAltitude: 6
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_18_Pickable_Charredskull
        prefab: Pickable_Charredskull
        biome: AshLands
        biomeArea: Edge,Median
        min: 20
        max: 40
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 2
        scaleMin: 1.3
        scaleMax: 1.4
        groundOffset: 0.2
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_19_Pickable_Pot_Shard
        prefab: Pickable_Pot_Shard
        biome: AshLands
        biomeArea: Median
        min: 4
        max: 6
        groupSizeMin: 4
        groupSizeMax: 6
        groupRadius: 20
        groundOffset: 0.75
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_20_Pickable_Ashstone
        prefab: Pickable_Ashstone
        biome: AshLands
        biomeArea: Median
        min: 7
        max: 15
        groupSizeMin: 10
        groupSizeMax: 20
        groupRadius: 40
        groundOffset: 0.1
        minAltitude: 30
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_21_ashland_pot2_red
        prefab: ashland_pot2_red
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 2
        groupSizeMin: 1
        groupSizeMax: 3
        groupRadius: 20
        groundOffset: -0.5
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 99
      - name: AshLands_22_UnstableLavaRock
        prefab: UnstableLavaRock
        biome: AshLands
        biomeArea: Edge,Median
        min: 1
        max: 1
        scaleMin: 0.7
        scaleMax: 1.2
        minAltitude: 1
        maxAltitude: 2000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 40
      - name: AshLands_23_Pickable_SmokePuff
        prefab: Pickable_SmokePuff
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 2
        groupSizeMin: 1
        groupSizeMax: 3
        groupRadius: 5
        minAltitude: 2
        maxAltitude: 2000
        minTerrainDelta: 0
        maxTerrainDelta: 0
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 60
      - name: AshLands_24_GraveStone_Broken_World
        prefab: GraveStone_Broken_World
        biome: AshLands
        biomeArea: Edge,Median
        min: 4
        max: 7
        groupSizeMin: 2
        groupSizeMax: 6
        groupRadius: 10
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 100
      - name: AshLands_25_Ashlands_ArchRoofDamaged
        prefab: Ashlands_ArchRoofDamaged
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 5
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 40
      - name: AshLands_26_Ashlands_Pillar4
        prefab: Ashlands_Pillar4
        biome: AshLands
        biomeArea: Edge,Median
        min: 3
        max: 6
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 20
        groundOffset: -1
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 40
      - name: AshLands_27_Ashlands_Ruins_Wall_Windows_Broken_4x6
        prefab: Ashlands_Ruins_Wall_Windows_Broken_4x6
        biome: AshLands
        biomeArea: Edge,Median
        min: 2
        max: 5
        groupSizeMin: 2
        groupSizeMax: 3
        groupRadius: 20
        minAltitude: 11
        maxAltitude: 1000
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 40

  defaultDeepNorth:
    entries:
      - name: DeepNorth_01_rock4_coast
        prefab: rock4_coast
        biome: DeepNorth
        biomeArea: Edge,Median
        min: 3
        max: 3
        groupSizeMin: 3
        groupSizeMax: 3
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: -0.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 2
        maxOceanDepth: 30
        minTilt: 0
        maxTilt: 90
      - name: DeepNorth_02_ice1
        prefab: ice1
        biome: DeepNorth
        biomeArea: Edge,Median
        min: 10
        max: 20
        snapToWater: true
        minAltitude: -1000
        maxAltitude: -1
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90
      - name: DeepNorth_03_ice_rock1
        prefab: ice_rock1
        biome: DeepNorth
        biomeArea: Edge,Median
        min: 0
        max: 1
        groundOffset: -2
        snapToWater: true
        minAltitude: -1000
        maxAltitude: -1
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90

  defaultOcean:
    entries:
      - name: Ocean_01_rock4_coast
        prefab: rock4_coast
        biome: Ocean
        biomeArea: Edge,Median
        min: 3
        max: 3
        groupSizeMin: 3
        groupSizeMax: 3
        groupRadius: 20
        scaleMin: 0.6
        scaleMax: 1.2
        minAltitude: -2
        maxAltitude: -0.5
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 2
        maxOceanDepth: 30
        minTilt: 0
        maxTilt: 90
      - name: Ocean_02_Leviathan
        prefab: Leviathan
        biome: Ocean
        biomeArea: Median
        min: 0
        max: 0.01
        snapToWater: true
        minAltitude: -1000
        maxAltitude: -30
        minTerrainDelta: 0
        maxTerrainDelta: 2
        terrainDeltaRadius: 0
        minOceanDepth: 0
        maxOceanDepth: 0
        minTilt: 0
        maxTilt: 90

  sparseMeadows:
    inherit: defaultMeadows
    entries:
      - name: Meadows_01_Beech1
        max: 3
        groupRadius: 8
      - name: Meadows_15_RaspberryBush
        enabled: false


";
    }
}
