- name: creative_terrain_modifier
  bools:
    - TerrainModifier.m_level, true
    - TerrainModifier.m_square, false
    - TerrainModifier.m_smooth, true
    - TerrainModifier.m_paintCleared, false
    - TerrainModifier.m_useTerrainCompiler, false
    - TerrainModifier.m_playerModifiction, false
  floats:
    - TerrainModifier.m_levelOffset, 0
    - TerrainModifier.m_levelRadius, 32
    - TerrainModifier.m_smoothRadius, 32
    - TerrainModifier.m_smoothPower, 4
- name: valheim_creative_siege_gateway_troll_gate_test
  strings:
    - SiegeGateway.m_siegeId, troll_gate_test
    - valheimCreativeSiegeId, troll_gate_test
    - tag, siege:troll_gate_test
  vecs:
    - SiegeGateway.m_entryPosition, 0,0,0
    - valheimCreativeSiegeEntryPosition, 0,0,0
